/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SortObject struct {
	Empty bool `json:"empty,omitempty"`
	Sorted bool `json:"sorted,omitempty"`
	Unsorted bool `json:"unsorted,omitempty"`
}
