/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PageMetadata struct {
	Size int64 `json:"size,omitempty"`
	TotalElements int64 `json:"totalElements,omitempty"`
	TotalPages int64 `json:"totalPages,omitempty"`
	Number int64 `json:"number,omitempty"`
}
