/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EntityModelComment struct {
	CommentId string `json:"commentId,omitempty"`
	CommentMessage string `json:"commentMessage"`
	CommentOwnerId string `json:"commentOwnerId"`
	CommentPostId string `json:"commentPostId"`
	CommentPublishDate string `json:"commentPublishDate,omitempty"`
	Links *map[string]Link `json:"_links,omitempty"`
}
