/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserDto struct {
	UserId string `json:"userId,omitempty"`
	UserTitle string `json:"userTitle,omitempty"`
	UserFirstName string `json:"userFirstName,omitempty"`
	UserLastName string `json:"userLastName,omitempty"`
	UserGender string `json:"userGender,omitempty"`
	UserEmail string `json:"userEmail,omitempty"`
	UserDateOfBirth string `json:"userDateOfBirth,omitempty"`
	UserRegisterDate string `json:"userRegisterDate,omitempty"`
	UserPhone string `json:"userPhone,omitempty"`
	UserPicture string `json:"userPicture,omitempty"`
	UserLocationId string `json:"userLocationId,omitempty"`
}
