/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CollectionModelEntityModelComment struct {
	Embedded *PagedModelEntityModelCommentEmbedded `json:"_embedded,omitempty"`
	Links *map[string]Link `json:"_links,omitempty"`
}
