/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Location struct {
	LocationId string `json:"locationId,omitempty"`
	LocationStreet string `json:"locationStreet,omitempty"`
	LocationCity string `json:"locationCity,omitempty"`
	LocationState string `json:"locationState,omitempty"`
	LocationCountry string `json:"locationCountry,omitempty"`
	LocationTimezone string `json:"locationTimezone,omitempty"`
}
