/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PageableObject struct {
	Offset int64 `json:"offset,omitempty"`
	Sort *SortObject `json:"sort,omitempty"`
	Unpaged bool `json:"unpaged,omitempty"`
	Paged bool `json:"paged,omitempty"`
	PageNumber int32 `json:"pageNumber,omitempty"`
	PageSize int32 `json:"pageSize,omitempty"`
}
