// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ynov.order.grpc;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   */
  String getProductId();
  /**
   * <code>string product_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   */
  String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int32 quantity = 4;</code>
   */
  int getQuantity();

  /**
   * <code>double price = 5;</code>
   */
  double getPrice();
}
