// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ynov.order.grpc;

public interface ProductByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.ProductByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   */
  String getProductId();
  /**
   * <code>string product_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();
}
