// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.ynov.product.grpc;

public final class ProductServiceProto {
  private ProductServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ProductByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ProductByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rproduct.proto\022\007product\"(\n\022ProductByIdR" +
      "equest\022\022\n\nproduct_id\030\001 \001(\t\"i\n\017ProductRes" +
      "ponse\022\022\n\nproduct_id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022" +
      "\023\n\013description\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\005\022\r" +
      "\n\005price\030\005 \001(\0012[\n\016ProductService\022I\n\016GetPr" +
      "oductById\022\033.product.ProductByIdRequest\032\030" +
      ".product.ProductResponse\"\000B.\n\025com.ynov.p" +
      "roduct.grpcB\023ProductServiceProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_product_ProductByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_product_ProductByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ProductByIdRequest_descriptor,
        new String[] { "ProductId", });
    internal_static_product_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_product_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ProductResponse_descriptor,
        new String[] { "ProductId", "Name", "Description", "Quantity", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
